version: "3"

services:
  mysql:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypass123
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build: .
    restart: unless-stopped
    image: cargo-loading
    ports:
      - "8080:8080"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s 
  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/deploy-pm2/nginx-default:/etc/nginx/sites-available/default
      - ./cert.key:/etc/nginx/cert.key
      - ./cert.crt:/etc/nginx/cert.crt